server:
  port: 9002
spring:
  application:
    name:  nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.118.130:3333
management:
  endpoints:
    web:
      exposure:
        include: "*"


